# Generated by Django 4.2.9 on 2024-01-18 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tool',
            fields=[
                ('drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=255)),
                ('drug_qty', models.IntegerField()),
                ('drug_exp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='tooltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.AddField(
            model_name='tool',
            name='drug_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool_app.tooltype'),
        ),
    ]
